apiVersion: apps/v1
kind: Deployment
metadata:
  name: applebite-deployment
  labels:
    app: applebite
spec:
  replicas: 3
  selector:
    matchLabels:
      app: applebite
  template:
    metadata:
      labels:
        app: applebite
    spec:
      containers:
        - name: applebite
          image: mangeshgot/apllebite:1
          ports:
            - containerPort: 5173
