apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "applebite.fullname" . }}-deployment
  labels:
    {{- include "applebite.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: applebite
  template:
    metadata:
      labels:
        {{- include "applebite.labels" . | nindent 8 }}
    spec:
      containers:
        - name: applebite
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.container.port }}
