apiVersion: v1
kind: Service
metadata:
  name: {{ include "applebite.fullname" . }}-service
  labels:
    {{- include "applebite.labels" . | nindent 4 }}
spec:
  selector:
    app: applebite
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
